version: '3.8'

services:
  # PHP Application Service
  app:
    build:
      context: .  
      dockerfile: ./docker/app/Dockerfile
    container_name: taskmanager_app
    working_dir: /var/www/html 
    volumes:
       - ./src:/var/www/html/src
       - ./app:/var/www/html/app
       - ./public:/var/www/html/public
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Read DB connection details from .env file
      DB_HOST: ${DB_HOST:-db} # Use default 'db' if not set in .env
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-tasks_db}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      NGINX_PORT: 8080
      WEB_ROOT: /var/www/html/public

  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: taskmanager_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-tasks_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations/create-tasks-table.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seeders/seed-tasks.sql:/docker-entrypoint-initdb.d/02_seeds.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: # Define the named volume for persistence